DROP TABLE ORDER_LINE_ITEM IF EXISTS;

CREATE TABLE ORDER_LINE_ITEM  (
   ID VARCHAR(36) NOT NULL PRIMARY KEY,
   QUANTITY INTEGER (20),
   PRICE DECIMAL (10,2),
   ORDER_ID VARCHAR(36),
   PRODUCT_ID VARCHAR (36)
);